######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 12 19:00:07 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += alu.h bus.h id.h io.h samos.h
SOURCES += alu.cpp bus.cpp id.cpp io.cpp main.cpp samos.cpp
